index:
    path: /
    controller: App\Controller\DefaultController::index

inicio:
    path: /juego/inicio
    controller: App\Controller\DefaultController::inicio
    defaults:
      template: 'index.html.twig'

logout:
    path: /juego/logout